# Generated by Django 6.0.4 on 2026-04-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_alter_profile_father_name_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
