# Generated by Django 6.0.4 on 2026-04-21 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_alter_profile_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binari', models.BinaryField(default=0)),
                ('big', models.BooleanField(default=True)),
                ('x', models.DurationField(verbose_name=datetime.timedelta(days=1, seconds=305))),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
