# Generated by Django 6.0.4 on 2026-04-21 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_test_alter_profile_national_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binari', models.BinaryField(default=0)),
                ('big', models.BooleanField(default=True)),
                ('x', models.DurationField(verbose_name=datetime.timedelta(days=1, seconds=305))),
                ('ee', models.IntegerField(max_length=44)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
