# Generated by Django 6.0.4 on 2026-04-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_alter_profile_national_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testt',
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
