# Generated by Django 5.2.7 on 2026-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0007_delete_testt_alter_profile_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.IntegerField(unique=True),
        ),
    ]
