# Generated by Django 5.2.7 on 2026-05-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0009_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
