# Generated by Django 5.2.7 on 2026-05-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0010_alter_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
