# Generated by Django 6.0.4 on 2026-04-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
