# Generated by Django 5.2.7 on 2026-04-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0006_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['create']},
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
