# Generated by Django 5.2.7 on 2026-04-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_alter_article_options_alter_article_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img',
            new_name='image',
        ),
    ]
