# Generated by Django 5.2.7 on 2026-04-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_rename_img_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['update'], 'verbose_name': 'Post', 'verbose_name_plural': 'Stories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='crated',
            new_name='created',
        ),
    ]
