# Generated by Django 5.2.7 on 2026-04-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0009_alter_article_options_rename_crated_category_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created',
            new_name='create',
        ),
    ]
