# Generated by Django 5.2.7 on 2026-05-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField()),
                ('body', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
