# Generated by Django 5.2.7 on 2026-05-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0012_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='title',
            new_name='name',
        ),
    ]
