# Generated by Django 5.2.7 on 2026-05-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0013_rename_title_input_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='input',
            options={'ordering': ['-date'], 'verbose_name': 'Massage', 'verbose_name_plural': 'CantactUs'},
        ),
    ]
