# Generated by Django 5.2.7 on 2026-05-11 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0014_alter_input_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 11, 19, 55, 53, 914475, tzinfo=datetime.timezone.utc)),
        ),
    ]
